language: csharp
dist: trusty
mono: none
dotnet: 1.0.1

script:
  - dotnet restore
  - dotnet build ./Mailjet.Client/Mailjet.Client.csproj -f netstandard1.1 -c Release
  - dotnet build ./Mailjet.ConsoleApplication/Mailjet.ConsoleApplication.csproj -c Release
  - dotnet test ./Mailjet.Tests/Mailjet.Tests.csproj -c Release